package packages.challenge;

public class Main {
    public static void main(String[] args) {
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//                GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
//        GO TO THE LIBRARYOFCHALLANGE AND USE IT AS INTERNAL PACKAGE THERE/
    }
}
